// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBLTsVJavfkZhqabtMU1E6WLwwlQz2aKr8',
//     appId: '1:1020643123653:android:f9a36f09c1798968606bac',
//     messagingSenderId: '1020643123653',
//     projectId: 'yunusco-system',
//     storageBucket: 'yunusco-system.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDddQI2cnxdBZVMbTFXXPtc3Ov-mF-zdbs',
//     appId: '1:1020643123653:ios:85c9250f7ad292e4606bac',
//     messagingSenderId: '1020643123653',
//     projectId: 'yunusco-system',
//     storageBucket: 'yunusco-system.firebasestorage.app',
//     androidClientId: '1020643123653-i7hnm79159l9ts7qicofnqrnu20bc6j8.apps.googleusercontent.com',
//     iosClientId: '1020643123653-tthh6hfslrj8mml1ib9bflp29lo0md3p.apps.googleusercontent.com',
//     iosBundleId: 'com.yunusco.accessories.yunuscoAccessories',
//   );
// }
